### ISSUE TITLE
Placement of R2 and C6

### ISSUE THREAD

**Issue by SukkoPera** [yeokm1/pcb-covox-amp#2]
Hi, first of all thanks for sharing your work!

I noticed that in your amplifier circuit, you took the output between R2 and C6:

![image](https://github.com/yeokm1/pcb-covox-amp/assets/1316870/86886450-92de-4f85-8779-f8e056c1f8b6)

while in Scott's original circuit, R2 and C6 were placed in series between the output and ground (here R1 and C2):

![image](https://github.com/yeokm1/pcb-covox-amp/assets/1316870/ed8dfaf3-9032-4159-a07d-80b337841773)

Can you explain which was the reason for that?

**Comment by yeokm1** [comment]
Oh yes, I think this is a mistake. I made this design 7 years ago 😅.

I don't think I will be fixing this mistake as I'm no longer using this project. But let me push a commit soon to explain the error.

**Comment by SukkoPera** [comment]
Oh ok, easy explanation then :). Thanks!

**Comment by yeokm1** [comment]
Mentioned this error in https://github.com/yeokm1/pcb-covox-amp/commit/813d431af90dc4b4537550a7beac57e9556295ce
